name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '00 15 * *'

env:
  ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
  ALIYUN_NAME_SPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
  ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
  ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Login to Aliyun
      run: docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

    - name: Pull and Push All Images
      run: |
        set +e
        
        while IFS= read -r line || [ -n "$line" ]; do
          [[ -z "$line" ]] && continue
          [[ "$line" =~ ^# ]] && continue

          echo "====================================="
          echo "正在处理：$line"

          docker pull $line

          image=$(echo "$line" | awk '{print $NF}')
          image="${image%%@*}"

          platform=$(echo "$line" | grep -o '--platform[ =][^ ]*' | head -1 | cut -d' ' -f2 | cut -d'=' -f2)
          if [ -n "$platform" ]; then
            prefix="${platform//\//_}_"
          else
            prefix=""
          fi

          name=$(echo "$image" | awk -F/ '{print $NF}')
          new="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$prefix$name"

          docker tag "$image" "$new"
          docker push "$new"

          docker rmi "$image" "$new"
          echo "✅ 同步完成：$new"
        done < images.txt
