name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '00 15 * * *'

env:
  ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
  ALIYUN_NAME_SPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
  ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
  ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Login to Aliyun
      run: docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

    - name: Pull and Push
      run: |
        set +e
        
        for img in nginx hello-world docker xhofe/alist:latest; do
          echo "正在同步：$img"
          docker pull $img
          name=$(echo $img | awk -F/ '{print $NF}')
          new=$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$name
          docker tag $img $new
          docker push $new
          docker rmi $img $new
          echo "同步完成：$new"
        done
