name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '00 15 * * *'  # 北京时间 23:00 自动同步

env:
  ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
  ALIYUN_NAME_SPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
  ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
  ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Login to Aliyun
      run: docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

    - name: Pull and Push All Images
      run: |
        while IFS= read -r line || [ -n "$line" ]; do
          [[ -z "$line" ]] && continue
          [[ "$line" =~ ^# ]] && continue

          echo "正在拉取: $line"
          docker pull $line

          image=$(echo "$line" | awk '{print $NF}')
          image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$image_name_tag"

          echo "正在标记: $new_image"
          docker tag "$image" "$new_image"

          echo "正在推送: $new_image"
          docker push "$new_image"

          docker rmi "$image" "$new_image"
        done < images.txt
